import { describe, it, expect } from 'vitest';
import { generateRemoteFile } from '../../src/generators/remote-file.js';
import type { MethodInfo } from '../../src/types.js';

describe('generateRemoteFile', () => {
	it('should generate GET handler using query', () => {
		const methods: MethodInfo[] = [{ method: 'GET', hasSchema: false }];
		const content = generateRemoteFile('-api.server', methods, 'hello');

		expect(content).toContain('import { query } from \'$app/server\';');
		expect(content).toContain('import { GET } from \'./-api.server\';');
		expect(content).toContain('export const hello_get = query(GET);');
		expect(content).not.toContain('command');
	});

	it('should generate POST handler using command', () => {
		const methods: MethodInfo[] = [{ method: 'POST', hasSchema: false }];
		const content = generateRemoteFile('-api.server', methods, 'users');

		expect(content).toContain('import { command } from \'$app/server\';');
		expect(content).toContain('import { POST } from \'./-api.server\';');
		expect(content).toContain('export const users_post = command(POST);');
		expect(content).not.toContain('query');
	});

	it('should generate GET with schema', () => {
		const methods: MethodInfo[] = [{ method: 'GET', hasSchema: true }];
		const content = generateRemoteFile('-api.server', methods, 'hello');

		expect(content).toContain('import { GET, zGET } from \'./-api.server\';');
		expect(content).toContain('export const hello_get = query(zGET, GET);');
	});

	it('should generate POST with schema', () => {
		const methods: MethodInfo[] = [{ method: 'POST', hasSchema: true }];
		const content = generateRemoteFile('-api.server', methods, 'users');

		expect(content).toContain('import { POST, zPOST } from \'./-api.server\';');
		expect(content).toContain('export const users_post = command(zPOST, POST);');
	});

	it('should use custom name from nMETHOD', () => {
		const methods: MethodInfo[] = [{ method: 'GET', hasSchema: false, customName: 'fetchUser' }];
		const content = generateRemoteFile('-api.server', methods, 'hello');

		expect(content).toContain('export const fetchUser = query(GET);');
		expect(content).not.toContain('hello_get');
	});

	it('should skip methods with empty customName', () => {
		const methods: MethodInfo[] = [
			{ method: 'GET', hasSchema: false, customName: '' },
			{ method: 'POST', hasSchema: false },
		];
		const content = generateRemoteFile('-api.server', methods, 'hello');

		expect(content).not.toContain('hello_get');
		expect(content).toContain('hello_post');
	});

	it('should import both query and command when needed', () => {
		const methods: MethodInfo[] = [
			{ method: 'GET', hasSchema: false },
			{ method: 'POST', hasSchema: false },
		];
		const content = generateRemoteFile('-api.server', methods, 'api');

		expect(content).toContain('import { query, command } from \'$app/server\';');
	});

	it('should handle multiple methods with mixed features', () => {
		const methods: MethodInfo[] = [
			{ method: 'GET', hasSchema: true },
			{ method: 'POST', hasSchema: true },
			{ method: 'DELETE', hasSchema: false, customName: 'removeUser' },
		];
		const content = generateRemoteFile('-api.server', methods, 'users');

		expect(content).toContain('users_get = query(zGET, GET)');
		expect(content).toContain('users_post = command(zPOST, POST)');
		expect(content).toContain('removeUser = command(DELETE)');
	});

	it('should include generated marker and eslint ignore', () => {
		const methods: MethodInfo[] = [{ method: 'GET', hasSchema: false }];
		const content = generateRemoteFile('-api.server', methods, 'hello');

		expect(content.startsWith('// @generated by @yuanlu_yl/vite-sveltekit-many-api')).toBe(true);
		expect(content).toContain('/* eslint-disable */');
	});

	it('should handle all HTTP methods', () => {
		const methods: MethodInfo[] = [
			{ method: 'GET', hasSchema: false },
			{ method: 'POST', hasSchema: false },
			{ method: 'PUT', hasSchema: false },
			{ method: 'PATCH', hasSchema: false },
			{ method: 'DELETE', hasSchema: false },
		];
		const content = generateRemoteFile('-api.server', methods, 'all_methods');

		expect(content).toContain('all_methods_get = query');
		expect(content).toContain('all_methods_post = command');
		expect(content).toContain('all_methods_put = command');
		expect(content).toContain('all_methods_patch = command');
		expect(content).toContain('all_methods_delete = command');
	});
});
