import { describe, it, expect } from 'vitest';
import { generateServerFile } from '../../src/generators/server-file.js';
import type { MethodInfo } from '../../src/types.js';

describe('generateServerFile', () => {
	it('should generate basic GET handler without schema', () => {
		const methods: MethodInfo[] = [{ method: 'GET', hasSchema: false }];
		const content = generateServerFile('-api.server', methods, '$lib/api/common.server');

		expect(content).toContain('import type { RequestHandler } from \'./$types\';');
		expect(content).toContain('import { success } from \'$lib/api/common.server\';');
		expect(content).toContain('import { GET as _GET } from \'./-api.server\';');
		expect(content).toContain('export const GET: RequestHandler = async () => {');
		expect(content).toContain('const data = await _GET();');
		expect(content).toContain('return success({ data });');
		expect(content).not.toContain('parseSearchParams');
		expect(content).not.toContain('parseBody');
	});

	it('should generate GET handler with schema using parseSearchParams', () => {
		const methods: MethodInfo[] = [{ method: 'GET', hasSchema: true }];
		const content = generateServerFile('-api.server', methods, '$lib/api/common.server');

		expect(content).toContain('import { success, parseSearchParams } from \'$lib/api/common.server\';');
		expect(content).toContain('import { GET as _GET, zGET } from \'./-api.server\';');
		expect(content).toContain('const params = await parseSearchParams(zGET);');
		expect(content).toContain('const data = await _GET(params);');
	});

	it('should generate POST handler with schema using parseBody', () => {
		const methods: MethodInfo[] = [{ method: 'POST', hasSchema: true }];
		const content = generateServerFile('-api.server', methods, '$lib/api/common.server');

		expect(content).toContain('import { success, parseBody } from \'$lib/api/common.server\';');
		expect(content).toContain('import { POST as _POST, zPOST } from \'./-api.server\';');
		expect(content).toContain('const params = await parseBody(zPOST);');
	});

	it('should import both parseBody and parseSearchParams when needed', () => {
		const methods: MethodInfo[] = [
			{ method: 'GET', hasSchema: true },
			{ method: 'POST', hasSchema: true },
		];
		const content = generateServerFile('-api.server', methods, '$lib/api/common.server');

		expect(content).toContain('import { success, parseBody, parseSearchParams } from \'$lib/api/common.server\';');
	});

	it('should not import parse helpers when no schema', () => {
		const methods: MethodInfo[] = [
			{ method: 'GET', hasSchema: false },
			{ method: 'POST', hasSchema: false },
		];
		const content = generateServerFile('-api.server', methods, '$lib/api/common.server');

		expect(content).toContain('import { success } from \'$lib/api/common.server\';');
		expect(content).not.toContain('parseBody');
		expect(content).not.toContain('parseSearchParams');
	});

	it('should handle PUT and PATCH with parseBody', () => {
		const methods: MethodInfo[] = [
			{ method: 'PUT', hasSchema: true },
			{ method: 'PATCH', hasSchema: true },
		];
		const content = generateServerFile('-api.server', methods, '$lib/api/common.server');

		expect(content).toContain('parseBody');
		expect(content).not.toContain('parseSearchParams');
	});

	it('should handle DELETE with parseSearchParams', () => {
		const methods: MethodInfo[] = [{ method: 'DELETE', hasSchema: true }];
		const content = generateServerFile('-api.server', methods, '$lib/api/common.server');

		expect(content).toContain('parseSearchParams');
		expect(content).not.toContain('parseBody');
	});

	it('should include generated marker and eslint ignore', () => {
		const methods: MethodInfo[] = [{ method: 'GET', hasSchema: false }];
		const content = generateServerFile('-api.server', methods, '$lib/api/common.server');

		expect(content.startsWith('// @generated by @yuanlu_yl/vite-sveltekit-many-api')).toBe(true);
		expect(content).toContain('/* eslint-disable */');
	});

	it('should use custom util import path', () => {
		const methods: MethodInfo[] = [{ method: 'GET', hasSchema: true }];
		const content = generateServerFile('-api.server', methods, '$api/common.server');

		expect(content).toContain('import { success, parseSearchParams } from \'$api/common.server\';');
	});
});
