/** SvelteKit 支持的 HTTP 方法 */
export const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as const;
export type HttpMethod = (typeof HTTP_METHODS)[number];

/** API 定义文件名 */
export const API_NAME = '-api.server.ts';

/** 生成文件标记，防止覆盖用户文件 */
export const GENERATED_MARKER = '// @generated by @yuanlu_yl/vite-sveltekit-many-api — DO NOT EDIT\n';
export const GENERATED_MARKER2 = '# @generated by @yuanlu_yl/vite-sveltekit-many-api — DO NOT EDIT\n';

export const ESLINT_IGNORE_ALL = '/* eslint-disable */\n';

/** 生成文件名 */
export const SERVER_FILE = '+server.ts';
export const REMOTE_FILE = 'api.remote.ts';
export const GITIGNORE_FILE = '.gitignore';

/** 注册表文件名 */
export const OPENAPI_REGISTRY_FILE = 'openapi-registry.server.ts';
export const MCP_REGISTRY_FILE = 'mcp-registry.server.ts';

/** API 路由根目录 */
export const API_ROUTES_DIR = 'src/routes/api';

/** .gitignore 内容 */
export const GITIGNORE_CONTENT = `/${SERVER_FILE}\n/${REMOTE_FILE}\n`;
export const API_GITIGNORE_ENTRY = `/${OPENAPI_REGISTRY_FILE}\n/${MCP_REGISTRY_FILE}\n`;

/** 日志前缀 */
export const LOG_PREFIX = '[api-routes]';

/** 判断方法是否使用请求体（而非查询参数） */
export function usesBody(method: HttpMethod): boolean {
	return method === 'POST' || method === 'PUT' || method === 'PATCH';
}

/** util 配置类型 */
export interface UtilConfig {
	/** 模板文件复制检测路径（为 null/undefined 时不做复制检测） */
	path?: string | null;
	/** 生成代码中的导入路径 */
	imp?: string;
	/** schema 模式：'standard'（默认）或 'zod' */
	schema?: 'standard' | 'zod';
}

/** 默认 util 配置 */
export const DEFAULT_UTIL_CONFIG: Required<Pick<UtilConfig, 'imp' | 'schema'>> &
	Pick<UtilConfig, 'path'> = {
	path: 'src/lib/api/common.server.ts',
	imp: '$lib/api/common.server',
	schema: 'standard',
};

/** 插件完整配置 */
export interface ApiRoutesConfig {
	util?: UtilConfig;
}
