/** SvelteKit 支持的 HTTP 方法 */
export const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as const;
export type HttpMethod = (typeof HTTP_METHODS)[number];

/** API 定义文件名 */
export const API_NAME = '-api.server.ts';

/** 生成文件标记，防止覆盖用户文件 */
export const GENERATED_MARKER = '// @generated by vite-plugin-api-routes — DO NOT EDIT\n';

export const ESLINT_IGNORE_ALL = '/* eslint-disable */\n';

/** 生成文件名 */
export const SERVER_FILE = '+server.ts';
export const REMOTE_FILE = 'api.remote.ts';
export const GITIGNORE_FILE = '.gitignore';

/** 注册表文件名 */
export const OPENAPI_REGISTRY_FILE = 'openapi-registry.server.ts';
export const MCP_REGISTRY_FILE = 'mcp-registry.server.ts';

/** API 路由根目录 */
export const API_ROUTES_DIR = 'src/routes/api';

/** .gitignore 内容 */
export const GITIGNORE_CONTENT = `/${SERVER_FILE}\n/${REMOTE_FILE}\n`;
export const API_GITIGNORE_ENTRY = `/${OPENAPI_REGISTRY_FILE}\n/${MCP_REGISTRY_FILE}\n`;

/** 日志前缀 */
export const LOG_PREFIX = '[api-routes]';

/** 判断方法是否使用请求体（而非查询参数） */
export function usesBody(method: HttpMethod): boolean {
	return method === 'POST' || method === 'PUT' || method === 'PATCH';
}
