/** SvelteKit 支持的 HTTP 方法 */
export const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as const;
export type HttpMethod = (typeof HTTP_METHODS)[number];

/** API 定义文件名 */
export const API_NAME = '-api.server.ts';

/** 生成文件标记，防止覆盖用户文件 */
export const GENERATED_MARKER = '// @generated by @yuanlu_yl/vite-sveltekit-many-api — DO NOT EDIT\n';
export const GENERATED_MARKER2 = '# @generated by @yuanlu_yl/vite-sveltekit-many-api — DO NOT EDIT\n';

export const ESLINT_IGNORE_ALL = '/* eslint-disable */\n';

/** 生成文件名 */
export const SERVER_FILE = '+server.ts';
export const REMOTE_FILE = 'api.remote.ts';
export const GITIGNORE_FILE = '.gitignore';

/** 注册表文件名 */
export const REGISTRY_FILE = 'registry.server.ts';
export const REGISTRY_MESSAGES_FILE = 'registry.messages.ts';

/** API 路由根目录（默认值；可通过 ApiRoutesConfig.apiDir 覆盖） */
export const API_ROUTES_DIR = 'src/routes/api';

/** 默认分组提取正则（字符串，运行时 new RegExp()） */
export const DEFAULT_GROUP_PATTERN = '/api/v[^/]+/([^/]+)';

export const API_GITIGNORE_ENTRY = `/${REGISTRY_FILE}\n/${REGISTRY_MESSAGES_FILE}\n`;

/** 日志前缀 */
export const LOG_PREFIX = '[api-routes]';

/** 判断方法是否使用请求体（而非查询参数） */
export function usesBody(method: HttpMethod): boolean {
	return method === 'POST' || method === 'PUT' || method === 'PATCH';
}

/** util 配置类型 */
export interface UtilConfig {
	/** 模板文件复制检测路径（为 null/undefined 时不做复制检测） */
	path?: string | null;
	/** 生成代码中的导入路径 */
	imp?: string;
	/** schema 模式：'standard'（默认）或 'zod' */
	schema?: 'standard' | 'zod';
}

/** 默认 util 配置 */
export const DEFAULT_UTIL_CONFIG: Required<Pick<UtilConfig, 'imp' | 'schema'>> & Pick<UtilConfig, 'path'> = {
	path: 'src/lib/api/common.server.ts',
	imp: '$lib/api/common.server',
	schema: 'standard',
};

/** i18n 分组标签文件配置 */
export interface MessagesConfig {
	/** 消息模块导入路径（默认 '$lib/paraglide/messages'） */
	from?: string;
	/** 导入的消息对象名（默认 'm'） */
	export?: string;
	/** 消息函数返回类型（默认 'string'） */
	returnType?: string;
	/** 键前缀（默认 'group'）；实际键为 '{keyPrefix}.{groupName}' */
	keyPrefix?: string;
}

/** 默认 messages 配置 */
export const DEFAULT_MESSAGES_CONFIG: Required<MessagesConfig> = {
	from: '$lib/paraglide/messages',
	export: 'm',
	returnType: 'string',
	keyPrefix: 'group',
};

/** 各类文件的生成开关 */
export interface GenerateConfig {
	/** 是否生成 +server.ts（默认 true） */
	server?: boolean;
	/** 是否生成 api.remote.ts（默认 true） */
	remote?: boolean;
	/** 是否生成 registry.server.ts（默认 true） */
	registry?: boolean;
	/** i18n 分组标签文件配置；false 或省略表示不生成（默认 false） */
	messages?: false | MessagesConfig;
}

/** 默认生成配置 */
export const DEFAULT_GENERATE_CONFIG: Required<Omit<GenerateConfig, 'messages'>> & Pick<GenerateConfig, 'messages'> = {
	server: true,
	remote: true,
	registry: true,
	messages: false,
};

/** 插件完整配置 */
export interface ApiRoutesConfig {
	util?: UtilConfig;
	/** 各类文件的生成开关 */
	generate?: GenerateConfig;
	/** API 路由根目录（默认 'src/routes/api'） */
	apiDir?: string;
	/** 从 API URL 提取分组的正则字符串（默认 '/api/v[^/]+/([^/]+)'） */
	groupPattern?: string;
}
